# Generated by Django 5.2.1 on 2025-09-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookshelf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
